// Generated by `yarn tsx scripts/build-sprites.ts` (`yarn sprites:build`). Do not edit by hand.
// Sprites point north and are drawn at PX_PER_M px per metre with the footprint centred in its cell.
// Draw the body atlas (vehicles.png, mask: true, tinted) and then the detail atlas
// (vehicle-details.png, unmasked) with the same position/angle and getSize = SPRITE_SIZE_M[type]
// in sizeUnits 'meters'; both cells share size and anchor so they overlay pixel-perfectly.

export const PX_PER_M = 16;

export const LIGHT_STATES = [
  'none',
  'brake',
  'left',
  'right',
  'brake-left',
  'brake-right',
] as const;
export type LightState = (typeof LIGHT_STATES)[number];

export interface BodyFrame {
  x: number;
  y: number;
  width: number;
  height: number;
  anchorX: number;
  anchorY: number;
  mask: true;
}
export interface DetailFrame {
  x: number;
  y: number;
  width: number;
  height: number;
  anchorX: number;
  anchorY: number;
  mask: false;
}

/** Body atlas (296×200): white silhouettes keyed `b{type}`. */
export const BODY_MAPPING: Record<string, BodyFrame> = {
  b0: { x: 0, y: 0, width: 30, height: 48, anchorX: 15, anchorY: 24, mask: true },
  b1: { x: 34, y: 0, width: 40, height: 58, anchorX: 20, anchorY: 29, mask: true },
  b2: { x: 78, y: 0, width: 46, height: 86, anchorX: 23, anchorY: 43, mask: true },
  b3: { x: 128, y: 0, width: 46, height: 86, anchorX: 23, anchorY: 43, mask: true },
  b4: { x: 178, y: 0, width: 58, height: 200, anchorX: 29, anchorY: 100, mask: true },
  b5: { x: 240, y: 0, width: 56, height: 160, anchorX: 28, anchorY: 80, mask: true },
};

/** Detail atlas (296×1220): overlays keyed `d{type}-{state}`. */
export const DETAIL_MAPPING: Record<string, DetailFrame> = {
  'd0-none': { x: 0, y: 0, width: 30, height: 48, anchorX: 15, anchorY: 24, mask: false },
  'd0-brake': { x: 0, y: 204, width: 30, height: 48, anchorX: 15, anchorY: 24, mask: false },
  'd0-left': { x: 0, y: 408, width: 30, height: 48, anchorX: 15, anchorY: 24, mask: false },
  'd0-right': { x: 0, y: 612, width: 30, height: 48, anchorX: 15, anchorY: 24, mask: false },
  'd0-brake-left': { x: 0, y: 816, width: 30, height: 48, anchorX: 15, anchorY: 24, mask: false },
  'd0-brake-right': { x: 0, y: 1020, width: 30, height: 48, anchorX: 15, anchorY: 24, mask: false },
  'd1-none': { x: 34, y: 0, width: 40, height: 58, anchorX: 20, anchorY: 29, mask: false },
  'd1-brake': { x: 34, y: 204, width: 40, height: 58, anchorX: 20, anchorY: 29, mask: false },
  'd1-left': { x: 34, y: 408, width: 40, height: 58, anchorX: 20, anchorY: 29, mask: false },
  'd1-right': { x: 34, y: 612, width: 40, height: 58, anchorX: 20, anchorY: 29, mask: false },
  'd1-brake-left': { x: 34, y: 816, width: 40, height: 58, anchorX: 20, anchorY: 29, mask: false },
  'd1-brake-right': {
    x: 34,
    y: 1020,
    width: 40,
    height: 58,
    anchorX: 20,
    anchorY: 29,
    mask: false,
  },
  'd2-none': { x: 78, y: 0, width: 46, height: 86, anchorX: 23, anchorY: 43, mask: false },
  'd2-brake': { x: 78, y: 204, width: 46, height: 86, anchorX: 23, anchorY: 43, mask: false },
  'd2-left': { x: 78, y: 408, width: 46, height: 86, anchorX: 23, anchorY: 43, mask: false },
  'd2-right': { x: 78, y: 612, width: 46, height: 86, anchorX: 23, anchorY: 43, mask: false },
  'd2-brake-left': { x: 78, y: 816, width: 46, height: 86, anchorX: 23, anchorY: 43, mask: false },
  'd2-brake-right': {
    x: 78,
    y: 1020,
    width: 46,
    height: 86,
    anchorX: 23,
    anchorY: 43,
    mask: false,
  },
  'd3-none': { x: 128, y: 0, width: 46, height: 86, anchorX: 23, anchorY: 43, mask: false },
  'd3-brake': { x: 128, y: 204, width: 46, height: 86, anchorX: 23, anchorY: 43, mask: false },
  'd3-left': { x: 128, y: 408, width: 46, height: 86, anchorX: 23, anchorY: 43, mask: false },
  'd3-right': { x: 128, y: 612, width: 46, height: 86, anchorX: 23, anchorY: 43, mask: false },
  'd3-brake-left': { x: 128, y: 816, width: 46, height: 86, anchorX: 23, anchorY: 43, mask: false },
  'd3-brake-right': {
    x: 128,
    y: 1020,
    width: 46,
    height: 86,
    anchorX: 23,
    anchorY: 43,
    mask: false,
  },
  'd4-none': { x: 178, y: 0, width: 58, height: 200, anchorX: 29, anchorY: 100, mask: false },
  'd4-brake': { x: 178, y: 204, width: 58, height: 200, anchorX: 29, anchorY: 100, mask: false },
  'd4-left': { x: 178, y: 408, width: 58, height: 200, anchorX: 29, anchorY: 100, mask: false },
  'd4-right': { x: 178, y: 612, width: 58, height: 200, anchorX: 29, anchorY: 100, mask: false },
  'd4-brake-left': {
    x: 178,
    y: 816,
    width: 58,
    height: 200,
    anchorX: 29,
    anchorY: 100,
    mask: false,
  },
  'd4-brake-right': {
    x: 178,
    y: 1020,
    width: 58,
    height: 200,
    anchorX: 29,
    anchorY: 100,
    mask: false,
  },
  'd5-none': { x: 240, y: 0, width: 56, height: 160, anchorX: 28, anchorY: 80, mask: false },
  'd5-brake': { x: 240, y: 204, width: 56, height: 160, anchorX: 28, anchorY: 80, mask: false },
  'd5-left': { x: 240, y: 408, width: 56, height: 160, anchorX: 28, anchorY: 80, mask: false },
  'd5-right': { x: 240, y: 612, width: 56, height: 160, anchorX: 28, anchorY: 80, mask: false },
  'd5-brake-left': {
    x: 240,
    y: 816,
    width: 56,
    height: 160,
    anchorX: 28,
    anchorY: 80,
    mask: false,
  },
  'd5-brake-right': {
    x: 240,
    y: 1020,
    width: 56,
    height: 160,
    anchorX: 28,
    anchorY: 80,
    mask: false,
  },
};

/** Cell height in metres per vehicle type: the IconLayer `getSize` for true scale. */
export const SPRITE_SIZE_M: number[] = [3, 3.625, 5.375, 5.375, 12.5, 10];

export const bodyIcon = (type: number) => `b${type}`;

/** Detail frame key; indicator -1 = left, 1 = right, 0 = off. */
export function detailIcon(type: number, braking: boolean, indicator: -1 | 0 | 1): string {
  const side = indicator < 0 ? 'left' : indicator > 0 ? 'right' : '';
  const state = braking ? (side ? `brake-${side}` : 'brake') : side || 'none';
  return `d${type}-${state}`;
}
