import { type VehicleTypeParams, type BehaviourParams } from './types';
const vehicle = (
  length: number,
  width: number,
  vMax: number,
  a: number,
  b: number,
  T: number,
  s0: number,
  canFilter: boolean,
  canUseVirtualLane: boolean,
): VehicleTypeParams => ({
  length,
  width,
  vMax: vMax / 3.6,
  a,
  b,
  T,
  s0,
  canFilter,
  canUseVirtualLane,
});
export const TYPE_PARAMS: VehicleTypeParams[] = [
  vehicle(2, 0.8, 60, 2.5, 3, 0.8, 1, true, true),
  vehicle(2.6, 1.4, 45, 1.2, 2.5, 1.2, 1.5, false, true),
  vehicle(4.3, 1.8, 70, 1.5, 2.5, 1.2, 2, false, true),
  vehicle(4.3, 1.8, 70, 1.8, 3, 1, 1.5, false, true),
  vehicle(11.5, 2.6, 50, 0.8, 2, 1.6, 3, false, false),
  vehicle(9, 2.5, 45, 0.6, 2, 1.8, 3, false, false),
];
export const BEHAVIOUR_PARAMS: BehaviourParams[] = [
  {
    politeness: 0.5,
    bSafe: 2,
    aThr: 0.3,
    lcCooldown: 8,
    gapFactor: 1,
    filterProb: 0.1,
    amberRunProb: 0.1,
    redRunProb: 0,
    reactionTime: 1,
    routeChangeProb: 0,
    busLaneViolationProb: 0,
  },
  {
    politeness: 0.2,
    bSafe: 3,
    aThr: 0.15,
    lcCooldown: 3,
    gapFactor: 0.7,
    filterProb: 0.6,
    amberRunProb: 0.5,
    redRunProb: 0.05,
    reactionTime: 0.8,
    routeChangeProb: 0.04,
    busLaneViolationProb: 0.08,
  },
  {
    politeness: 0,
    bSafe: 4,
    aThr: 0.05,
    lcCooldown: 1,
    gapFactor: 0.45,
    filterProb: 0.9,
    amberRunProb: 0.9,
    redRunProb: 0.2,
    reactionTime: 0.6,
    routeChangeProb: 0.15,
    busLaneViolationProb: 0.25,
  },
];
